export const loremIpsum = `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus rhoncus. Phasellus et lorem id felis nonummy placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Sed ac dolor sit amet purus malesuada congue. Duis pulvinar. Aenean vel massa quis mauris vehicula lacinia. Etiam posuere lacus quis dolor. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Fusce suscipit libero eget elit. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Quisque porta. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?

Nunc dapibus tortor vel mi dapibus sollicitudin. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas lorem. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Etiam bibendum elit eget erat. Integer pellentesque quam vel velit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam in lorem sit amet leo accumsan lacinia. Nullam rhoncus aliquam metus.

Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Vestibulum fermentum tortor id mi. Integer malesuada. Duis viverra diam non justo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Phasellus et lorem id felis nonummy placerat. In rutrum. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Fusce wisi. In rutrum. Etiam egestas wisi a erat. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Aliquam erat volutpat. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Fusce aliquam vestibulum ipsum. Et harum quidem rerum facilis est et expedita distinctio.

In enim a arcu imperdiet malesuada. Vestibulum fermentum tortor id mi. Etiam bibendum elit eget erat. Suspendisse sagittis ultrices augue. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nullam faucibus mi quis velit. Nulla pulvinar eleifend sem. Quisque porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Curabitur vitae diam non enim vestibulum interdum. Nulla non arcu lacinia neque faucibus fringilla. Etiam egestas wisi a erat. Cras elementum. Nullam sit amet magna in magna gravida vehicula. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Nunc dapibus tortor vel mi dapibus sollicitudin. Et harum quidem rerum facilis est et expedita distinctio.

Aliquam id dolor. In dapibus augue non sapien. Maecenas libero. Phasellus et lorem id felis nonummy placerat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nulla est. Etiam posuere lacus quis dolor. Phasellus rhoncus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. In enim a arcu imperdiet malesuada. Integer tempor. Nullam sit amet magna in magna gravida vehicula. Curabitur sagittis hendrerit ante. Nam sed tellus id magna elementum tincidunt. Nulla est. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim.`
